name: insar-full
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.0=h59ae206_7
  - aws-c-cal=0.9.0=h5e3027f_1
  - aws-c-common=0.12.3=hb9d3cd8_0
  - aws-c-compression=0.3.1=hafb2847_5
  - aws-c-event-stream=0.5.4=h2dcaabb_9
  - aws-c-http=0.10.1=hb50fa74_1
  - aws-c-io=0.19.0=h7962f60_2
  - aws-c-mqtt=0.13.0=h35de22e_3
  - aws-c-s3=0.7.17=h50d7d24_2
  - aws-c-sdkutils=0.2.3=hafb2847_5
  - aws-checksums=0.2.7=hafb2847_1
  - aws-crt-cpp=0.32.5=h2811929_3
  - aws-sdk-cpp=1.11.510=hffe9a0f_8
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - blosc=1.21.6=he440d0b_1
  - brotli-python=1.1.0=py39hf88036b_3
  - brunsli=0.1=he3183e4_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - c-blosc2=2.15.2=h3122c55_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - capnproto=1.0.2=h766bdaa_3
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - cfitsio=4.6.2=ha0b56bc_1
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - expat=2.7.4=h7354ed3_0
  - fftw=3.3.10=nompi_h3b011a4_111
  - fmt=11.1.4=h07f6e7f_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - gdal=3.10.3=py39h231787c_13
  - geos=3.13.1=h97f6797_0
  - geotiff=1.7.4=h239500f_2
  - giflib=5.2.2=hd590300_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py39h63168ba_100
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h19486de_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.12.30=py39hac51188_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - isce2=2.6.4=py39hd75e264_2
  - json-c=0.18=h6688a6e_0
  - jxrlib=1.1=hd590300_3
  - kealib=1.6.2=hb2f3951_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libacl=2.3.2=h0f662aa_0
  - libaec=1.1.5=h088129d_0
  - libarchive=3.7.7=h75ea233_4
  - libavif16=1.3.0=h316e467_3
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.23=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal=3.10.3=h3b705f5_27
  - libgdal-core=3.10.3=hab2de9c_5
  - libgdal-fits=3.10.3=hd249192_5
  - libgdal-grib=3.10.3=h928e5b2_5
  - libgdal-hdf4=3.10.3=h9f77858_5
  - libgdal-hdf5=3.10.3=heb3e146_5
  - libgdal-jp2openjpeg=3.10.3=h021fd61_5
  - libgdal-kea=3.10.3=hb47621c_5
  - libgdal-netcdf=3.10.3=hda9de04_5
  - libgdal-pdf=3.10.3=h7544357_5
  - libgdal-pg=3.10.3=h371d8d8_5
  - libgdal-postgisraster=3.10.3=h371d8d8_5
  - libgdal-tiledb=3.10.3=h7fe9b51_5
  - libgdal-xls=3.10.3=hbf74d7f_5
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran-ng=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgrpc=1.71.0=h8e591d7_1
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=h6cb5226_4
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnetcdf=4.9.2=nompi_h21f7587_118
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.55=h421ea60_0
  - libpq=17.6=h3675c94_1
  - libprotobuf=5.29.3=h7460b1f_3
  - libre2-11=2025.06.26=hba17884_0
  - librttopo=1.1.0=hd718a1a_18
  - libspatialite=5.1.0=he17ca71_14
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=hd9ff511_4
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h04c0eec_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - minizip=4.0.10=h05a5f5f_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numpy=1.26.4=py39h474f0d3_0
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openmotif=2.3.8=hf55c2fc_5
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.44=hc749103_2
  - pillow=11.3.0=py39h15c0740_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - poppler=24.12.0=hd7b24de_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=17.6=h021f68a_1
  - proj=9.6.2=h18fbb6c_2
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python_abi=3.9=8_cp39
  - pywavelets=1.6.0=py39hd92a3bb_0
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.06.26=h9925aae_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.5.18=h763c568_1
  - scikit-image=0.24.0=py39h3b40f6f_3
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=py39h06a4308_0
  - snappy=1.2.2=h03e3b7b_1
  - spdlog=1.15.3=h10b92b3_0
  - sqlite=3.51.1=he0a8d7e_0
  - svt-av1=4.0.0=hecca717_0
  - tifffile=2024.6.18=pyhd8ed1ab_0
  - tiledb=2.27.2=h04be07c_7
  - tk=8.6.15=h54e0aa7_0
  - tzcode=2025c=hb03c661_0
  - tzdata=2025c=he532380_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py39h06a4308_0
  - xerces-c=3.2.5=h988505b_2
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxft=2.3.9=h355ab9f_0
  - xorg-libxmu=1.3.1=hb03c661_0
  - xorg-libxp=1.0.4=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zfp=1.0.1=h909a3a2_5
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.2.5=hde8ca8f_1
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - argcomplete==3.6.3
      - attrs==25.4.0
      - cartopy==0.23.0
      - cdsapi==0.7.7
      - click==8.1.8
      - cloudpickle==3.1.2
      - configobj==5.0.9
      - contourpy==1.3.0
      - cvxopt==1.3.3
      - cycler==0.12.1
      - dask==2024.8.0
      - dask-jobqueue==0.8.5
      - distributed==2024.8.0
      - donfig==0.8.1.post1
      - ecmwf-datastores-client==0.4.2
      - fonttools==4.60.2
      - fsspec==2025.10.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.7
      - locket==1.0.0
      - lxml==6.0.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mintpy==1.6.3
      - msgpack==1.1.2
      - multiurl==0.3.7
      - partd==1.4.2
      - platformdirs==4.4.0
      - psutil==7.2.2
      - pyaps3==0.3.7
      - pygments==2.19.2
      - pygrib==2.1.6
      - pykdtree==1.4.3
      - pykml==0.2.0
      - pyparsing==3.3.2
      - pyproj==3.6.1
      - pyresample==1.31.0
      - pyshp==3.0.3
      - pysolid==0.3.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rich==14.3.2
      - shapely==2.0.7
      - six==1.17.0
      - sortedcontainers==2.4.0
      - tblib==3.2.2
      - toolz==1.1.0
      - tornado==6.5.4
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - utm==0.8.1
      - zict==3.0.0
prefix: /home/faraz/anaconda3/envs/insar-full
